version: 2

models: 
  - name: staging_jobs
    description: "A staging model to retrieve the data from dbt"
    columns: 
      - name: company_name
        description: "The name of the company"
        data_tests: 
          - not_null
      - name: job_title
        description: "The position advertised in the listing"
      - name: location
        description: "The location of the position"
        data_tests: 
          - not_null
      - name: min_salary
        description: "The minimum amount in the salary range, or 'Not communicated'"
        data_tests: 
          - not_null
      - name: max_salary
        description: "The maximum amount in the salary range, or 'Not communicated'"
        data_tests: 
          - not_null
      - name: tech_stack
        description: "A list of technical requirements for the position"
      - name: listing_url
        description: "The URL of the listing"
      - name: date_posted
        description: "The date on which the listing was created"
      - name: categories
        description: "The categories of the listing"
      - name: company_activity
        description: "The main activity of the company"
      - name: company_sector
        description: "The main sector of the company"
      - name: company_central_office
        description: "The central office location"
      - name: company_creation_date
        description: "The year of creation of the company"
      - name: number_employees
        description: "The total number of employees of the company internationally"
      - name: implemented_in_bulgaria_date
        description: "The year of implementation of the company in Bulgaria"
      - name: number_employees_in_bulgaria
        description: "The total number of employees in Bulgaria"
      - name: offices_in_bulgaria
        description: "The cities where the company has offices in Bulgaria"
      - name: it_employees_in_bulgaria
        description: "The number of employees in the IT departement of the company in Bulgaria"
      - name: date_scraped
        description: "The date on which the listing was scraped"
