version: '2'

models:
  - name: dim_location
    description: "A list of the unique locations contained in the scraped listings"
    columns:
      - name: location_id
        description: "The identifier of the location"
      - name: location_name
        description: "The city name of WFH situation"
  - name: dim_date
    description: "A table representing the date dimension"
    columns: 
      - name: date_id
        description: "The identifier of the date"
        tests: 
          - unique 
          - not_null
      - name: day
        description: "The day part of the date"
      - name: month
        description: "The month part of the date"
      - name: year
        description: "The year part of the date"
      - name: week
        description: "The week number of the year"
      - name: weekday
        description: "The week days's full name"
      - name: is_weekend
        description: "Indicates if the day is a weekend day or not"
  - name: dim_company
    description: "Dimension representing the company of the listing"
    columns: 
      - name: company_id
        description: "The technical ID of the row"
        tests: 
          - unique
          - not_null
      - name: company_name
        description: "The name of the company"
        tests: 
          - unique
          - not_null
  - name: fact_listings
    description: "The jobs listings fact table"
    columns:
      - name: listing_id
        description: "The id of the listing based on URL and date scraped"
        tests: 
          - unique
          - not_null
      - name: company_id
        description: "The identifier of the company to dim_company"
      - name: job_title
        description: "The name of the position"
      - name: location_id
        description: "The id of the location to dim_location"
      - name: min_salary
        description: "The minimum salary proposed"
      - name: max_salary
        description: "The maximum salary proposed"
      - name: listing_url
        description: "The URL of the listing on dev.bg"
      - name: description
        description: "The description of the position"
      - name: date_posted_id
        description: "The ID of the date on which the listing was posted"
      - name: date_scraped_id 
        description: "The ID of the date on which the listing was scraped"
