version: '2'

models:
  - name: dim_location
    description: "A list of the unique locations contained in the scraped listings"
    columns:
      - name: location_name
        description: "The city name of WFH situation"
  - name: dim_date
    description: "A table representing the date dimension"
    columns: 
      - name: date_id
        description: "The identifier of the date"
        tests: 
          - unique 
          - not_null
      - name: day
        description: "The day part of the date"
      - name: month
        description: "The month part of the date"
      - name: year
        description: "The year part of the date"
      - name: week
        description: "The week number of the year"
      - name: weekday
        description: "The week days's full name"
      - name: is_weekend
        description: "Indicates if the day is a weekend day or not"
  - name: dim_company
    description: "Dimension representing the company of the listing"
    columns: 
      - name: company_name
        description: "The name of the company"
        tests: 
          - unique
          - not_null
